### ISSUE TITLE
Progress bar is above hover exp

### ISSUE THREAD

**Issue by Zyphs** [m0bilebtw/skills-tab-progress-bars#1]
The bar is always on top even the remaining exp box when you hover over the skill.

![Untitled](https://user-images.githubusercontent.com/10115774/77248022-93af6280-6c36-11ea-9588-69f659df51ff.png)

**Comment by m0bilebtw** [comment]
I am aware of this - unfortunately RuneLite currently provides no layer
between 'above all widgets' and 'below widgets', meaning a solution to this
is not quite as simple as it could be.

I'll continue to consider options while checking the layer options for any
changes, though I don't believe they're planning on adding the ideal
intermediate layer, it being a non-trivial change and likely rarely used
option, so a custom solution is probably required and this won't
necessarily be an easy one.

**Comment by luna-duclos** [comment]
A cheap dirty hack might be to color that space yellow manually in the plugin rather than try and layer it all correctly.

**Comment by m0bilebtw** [comment]
Unfortunately with configurable bar height, it can cover the text of the tooltip too, so that would only really help for short bars.

I'm considering trying to hook in to mouse hover events so that all bars will show by default, but while hovering a skill, only that skill's bar will show. The bar is contained entirely within the skill widget so should never overlap with the tooltip itself, and you can still see all the bars at once while not hovering over the skills. 

**_If I can get mouse hover events for the skill widgets_**, does that seem like a reasonable solution?
