### ISSUE TITLE
[Shattered Relics League] Progress bars don't render.

### ISSUE THREAD

**Issue by Feiioury** [m0bilebtw/skills-tab-progress-bars#15]
As per the title, the progress bars within the skills tab doesn't seem to render at all whilst on a "Leagues III" server.

Here's a screenshot: 
![image](https://user-images.githubusercontent.com/19168008/150664434-44bb0808-a2e0-4d49-ba4a-fa8fae0c0e96.png)

I tried uninstalling the plugin, and then re-installing it to see if maybe something had broken on my end. However since it's still not working, I figured I should open an issue on the GitHub repository here.

**Comment by iawhd** [comment]
It's also broken for me. Guessing it's to do with the locked skills?

**Comment by m0bilebtw** [comment]
This is specifically a leagues world issue. The script that the client runs to initialise the skills tab usually happens when you login. On leagues, (perhaps because of locked skills but honestly it seems more like a bug from jagex) it runs multiple tens of times **per tick**, _while the skills tab is open._ The skill widgets on leagues still have the same IDs as main game so the bars are actually still being created and put in the right places, they're just also being wrecked by this constant re-initialisation by the script that should only have been run once.
