### ISSUE TITLE
Add an option to only show the skill progress bars for "Goals" only

### ISSUE THREAD

**Issue by 07Arab** [m0bilebtw/skills-tab-progress-bars#9]
^Basically what the title suggests.

Just an option to show the progress to goals, while NOT showing progress to levels. Possibly even separate the goal bar and the progress to levels bar (1 on top and the other on the bottom possibly?)

Thanks in advance!

**Comment by 07Arab** [comment]
I believe this has now been added @m0bilebtw , thanks for the addition!

**Comment by m0bilebtw** [comment]
I actually haven't added this, but I am testing it now.

Separating the bars so that one is on top of the skill and the other is on the bottom can look a little confusing as one bar from one skill looks attached to the other bar from the skill above/below it, so I will keep both bars at the bottom, stacked on each other. 

However, I am happy with adding the option "Show ONLY goals progress" (off by default) which will hide the progress bars for levels and only show goals set using the in-game menu. Using this option will snap the goals bars to the bottom of the skill widget, taking up the space that the progress to level bar *would have* taken up.

**Comment by m0bilebtw** [comment]
Update awaiting approval into the plugin-hub here runelite/plugin-hub#2134
